from pathlib import Path
import os, sys
import platform
import subprocess
"""
  The default cross-compilation toolchain can be specified in a 
  custom `config_defaults.mk` file and passed via the `CONFIG_DEFAULT_FILE` 
  environment variable.

export CONFIG_DEFAULT_FILE=linux_x86_cross_cp0_config_defaults.mk
scons -j8
"""


cross_package_enabled = False
version = "v0.0.4"
local_path = Path(os.getcwd())
sdk_path = local_path.parent.parent / "SDK"
static_lib_path = sdk_path / "github_source" / f"static_lib_{version}"

if os.environ.get("CardputerZero", '') == 'y':
    os.environ["CONFIG_DEFAULT_FILE"] = "linux_x86_cross_cp0_config_defaults.mk"

if os.environ.get("CONFIG_DEFAULT_FILE") == None:
    if platform.machine() == 'x86_64':
        os.environ["CONFIG_DEFAULT_FILE"] = "linux_x86_sdl2_config_defaults.mk"

if "cross" in os.environ.get("CONFIG_DEFAULT_FILE", ''):
    cross_package_enabled = True
    config_tmp_path = Path("build") / "config" / "config_tmp.mk"
    sysroot_path_str = static_lib_path.as_posix().replace('"', r'\"')
    config_tmp_content = (
        f'CONFIG_TOOLCHAIN_SYSROOT="{sysroot_path_str}"\n'
    )
    if not config_tmp_path.exists() or config_tmp_path.read_text() != config_tmp_content:
        config_tmp_path.parent.mkdir(parents=True, exist_ok=True)
        config_tmp_path.write_text(config_tmp_content)

os.environ["SDK_PATH"] = str(sdk_path)
os.environ["EXT_COMPONENTS_PATH"] = str(sdk_path.parent / "ext_components")

env = SConscript(
    str(sdk_path / "tools" / "scons" / "project.py"),
    variant_dir=os.getcwd(),
    duplicate=0,
)

# static_lib is only needed for cross-compilation, skip in SDL mode.
if cross_package_enabled:
    update = False
    if not static_lib_path.exists():
        update = True
    else:
        try:
            with open(str(static_lib_path / "version"), "r") as f:
                if version != f.read().strip():
                    update = True
        except Exception:
            update = True

    if update:
        with open(env["PROJECT_TOOL_S"]) as f:
            exec(f.read())
        try:
            import tarfile

            tarfile.TarFile.extraction_filter = staticmethod(
                tarfile.fully_trusted_filter
            )
        except AttributeError:
            pass
        down_url = (
            "https://github.com/CardputerZero/M5CardputerZero-UserDemo/"
            "releases/download/{}/sdk_bsp.tar.gz"
        ).format(version)
        check_wget_down(down_url, "static_lib_{}.tar.gz".format(version))
