[ssh]
local_file_path = dist
remote_file_path = /home/pi/dist
remote_host = 192.168.28.114
remote_port = 22
username = pi
password = pi
; before_cmd = 'echo pi |  sudo -S systemctl stop APPLaunch.service'
after_cmd = 'systemctl --user stop APPLaunch.service; echo pi | sudo -S mkdir -p /usr/share/APPLaunch/bin; echo pi | sudo -S cp -a /home/pi/dist/APPLaunch/. /usr/share/APPLaunch/; echo pi | sudo -S install -m 755 /home/pi/dist/M5CardputerZero-APPLaunch /usr/share/APPLaunch/bin/M5CardputerZero-APPLaunch; systemctl --user start APPLaunch.service'
