import os

Import('env')
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())

SRCS = Glob('src/*.c*')
SRCS += append_srcs_dir(ADir('ui'))

INCLUDE = [ADir('.'), ADir('include'), ADir('ui')]
PRIVATE_INCLUDE = []
REQUIREMENTS = ['cp0_lvgl', 'lvgl_component', 'pthread', 'Sigslot', 'eventpp', 'RadioLib']
STATIC_LIB = []
DYNAMIC_LIB = []
DEFINITIONS = []
DEFINITIONS_PRIVATE = []
LDFLAGS = []
LINK_SEARCH_PATH = []
STATIC_FILES = [ADir('../APPLaunch')]

lvgl_component = list(filter(lambda x: x['target'] == 'lvgl_component', env['COMPONENTS']))[0]
toolchain_sysroot = os.environ.get('CONFIG_TOOLCHAIN_SYSROOT', '') or '/'

if 'CONFIG_V9_5_LV_USE_SDL' in os.environ:
    lvgl_component['REQUIREMENTS'] += ['SDL2']
    lvgl_component['INCLUDE'] += ['/usr/include/SDL2']
    lvgl_component['DEFINITIONS'] += ['-D_REENTRANT']

if 'CONFIG_V9_5_LV_USE_FREETYPE' in os.environ:
    lvgl_component['REQUIREMENTS'] += ['freetype']
    lvgl_component['INCLUDE'] += [
        f"{os.path.join(toolchain_sysroot, 'usr', 'include', 'freetype2')}",
        f"{os.path.join(toolchain_sysroot, 'usr', 'include', 'libpng16')}",
    ]

env['COMPONENTS'].append({
    'target': env['PROJECT_NAME'],
    'SRCS': SRCS,
    'INCLUDE': INCLUDE,
    'PRIVATE_INCLUDE': PRIVATE_INCLUDE,
    'REQUIREMENTS': REQUIREMENTS,
    'STATIC_LIB': STATIC_LIB,
    'DYNAMIC_LIB': DYNAMIC_LIB,
    'DEFINITIONS': DEFINITIONS,
    'DEFINITIONS_PRIVATE': DEFINITIONS_PRIVATE,
    'LDFLAGS': LDFLAGS,
    'LINK_SEARCH_PATH': LINK_SEARCH_PATH,
    'STATIC_FILES': STATIC_FILES,
    'REGISTER': 'project',
})
