# component/SConscript
Import("env")
import os

with open(env["PROJECT_TOOL_S"]) as f:
    exec(f.read())

env["GIT_REPO_LISTS"]["Sigslot"] = {
    "url": "https://github.com/palacaze/sigslot.git",
    "commit": "b588b791b9cf7eb17ff0a74d8aebd4a61166c2e1",
    "path": os.path.join(os.environ['GIT_REPO_PATH'], "sigslot"),
}

if "CONFIG_SIGSLOT_COMPONENT_ENABLED" in os.environ:
    c_path = check_component("Sigslot")
    SRCS = []
    INCLUDE = [os.path.join(c_path, 'include')]
    PRIVATE_INCLUDE = []
    REQUIREMENTS = []
    STATIC_LIB = []
    DYNAMIC_LIB = []
    DEFINITIONS = []
    DEFINITIONS_PRIVATE = []
    LDFLAGS = []
    LINK_SEARCH_PATH = []

    env["COMPONENTS"].append(
        {
            "target": os.path.basename(env["component_dir"]),
            "SRCS": SRCS,
            "INCLUDE": INCLUDE,
            "PRIVATE_INCLUDE": PRIVATE_INCLUDE,
            "REQUIREMENTS": REQUIREMENTS,
            "STATIC_LIB": STATIC_LIB,
            "DYNAMIC_LIB": DYNAMIC_LIB,
            "DEFINITIONS": DEFINITIONS,
            "DEFINITIONS_PRIVATE": DEFINITIONS_PRIVATE,
            "LDFLAGS": LDFLAGS,
            "LINK_SEARCH_PATH": LINK_SEARCH_PATH,
            "REGISTER": "static",
        }
    )
