// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#ifndef _UI_COMP__H
#define _UI_COMP__H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif



#if LVGL_VERSION_MAJOR >= 9
    #define lv_tabview_create_compat(parent, dir, size) \
        ({ \
            lv_obj_t *_tv = lv_tabview_create(parent); \
            lv_tabview_set_tab_bar_position(_tv, dir); \
            lv_tabview_set_tab_bar_size(_tv, size); \
            _tv; \
        })
#else
    #define lv_tabview_create_compat(parent, dir, size) \
        lv_tabview_create(parent, dir, size)
#endif
// #define lv_tabview_create lv_tabview_create_compat



typedef struct {
    uint32_t keysym;      // X11/自定义键码，或 0
    uint16_t mods;        // Ctrl/Alt/Shift...
    uint8_t  utf8[8];     // 完整 UTF-8 字节序列
} term_key_evt_t;

void get_component_child_event_cb(lv_event_t * e);
void del_component_child_event_cb(lv_event_t * e);

lv_obj_t * ui_comp_get_child(lv_obj_t * comp, uint32_t child_idx);
extern uint32_t LV_EVENT_GET_COMP_CHILD;
extern uint32_t LV_EVENT_KEYBOARD;
#include "ui_comp_button1.h"














#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
