import os

Import("env")
with open(env["PROJECT_TOOL_S"]) as f:
    exec(f.read())


SRCS = Glob("src/*.c*")
INCLUDE = [ADir("."), ADir("include")]
PRIVATE_INCLUDE = []
REQUIREMENTS = ["cp0_lvgl", "eventpp", "lvgl_component", "pthread"]
STATIC_LIB = []
DYNAMIC_LIB = []
DEFINITIONS = []
DEFINITIONS_PRIVATE = []
LDFLAGS = []
LINK_SEARCH_PATH = []
STATIC_FILES = []

SRCS += append_srcs_dir(ADir("ui"))
INCLUDE += ["ui"]

lvgl_component = list(
    filter(lambda x: x["target"] == "lvgl_component", env["COMPONENTS"])
)[0]
if "CONFIG_USERDEMO_LINUX_X86_SDL2" in os.environ:
    REQUIREMENTS += pkg_config_ldflags("sdl2")
    DEFINITIONS += pkg_config_cflags("sdl2")
    lvgl_component["DEFINITIONS"] += pkg_config_cflags("sdl2")
    lvgl_component["DEFINITIONS"] += ["-D_REENTRANT"]

if "CONFIG_USERDEMO_LINUX_CP0" in os.environ:
    REQUIREMENTS += ["input", "xkbcommon", "udev"]

env["COMPONENTS"].append(
    {
        "target": "M5CardputerZero-UserDemo",
        "SRCS": SRCS,
        "INCLUDE": INCLUDE,
        "PRIVATE_INCLUDE": PRIVATE_INCLUDE,
        "REQUIREMENTS": REQUIREMENTS,
        "STATIC_LIB": STATIC_LIB,
        "DYNAMIC_LIB": DYNAMIC_LIB,
        "DEFINITIONS": DEFINITIONS,
        "DEFINITIONS_PRIVATE": DEFINITIONS_PRIVATE,
        "LDFLAGS": LDFLAGS,
        "LINK_SEARCH_PATH": LINK_SEARCH_PATH,
        "STATIC_FILES": STATIC_FILES,
        "REGISTER": "project",
    }
)
