# component/SConscript
Import("env")
import os
from pathlib import Path

with open(env["PROJECT_TOOL_S"]) as f:
    exec(f.read())

def toolchain_path(*parts):
    return Path(os.environ.get("CONFIG_TOOLCHAIN_SYSROOT", "")).joinpath(*parts)


if "CONFIG_CP0_LVGL_COMPONENT_ENABLED" in os.environ or "CONFIG_SIGSLOT_COMPONENT_ENABLED" in os.environ:
    SRCS = []
    INCLUDE = [ADir('include')]
    PRIVATE_INCLUDE = []
    REQUIREMENTS = ['lvgl_component', 'eventpp', 'Miniaudio', 'RadioLib']
    STATIC_LIB = []
    DYNAMIC_LIB = []
    DEFINITIONS = []
    DEFINITIONS_PRIVATE = []
    LDFLAGS = []
    LINK_SEARCH_PATH = []
    SRCS += Glob('src/*.c*')
    if 'CONFIG_V9_5_LV_USE_SDL' in os.environ:
        DEFINITIONS += ['-DHAL_PLATFORM_SDL=1']
        DEFINITIONS += pkg_config_cflags('sdl2')
        REQUIREMENTS += pkg_config_ldflags('sdl2')
        SRCS += Glob('src/sdl/*.c*')
    else:
        SRCS += Glob('src/cp0/*.c*')
        REQUIREMENTS += ['input', 'xkbcommon', 'udev', 'pthread']
        REQUIREMENTS += [':libdbus-1.so.3']
        REQUIREMENTS += ['camera', 'camera-base', 'jpeg']
        PRIVATE_INCLUDE += [toolchain_path('usr', 'include', 'dbus-1.0'),
                            toolchain_path('usr', 'lib', env.get('GCC_DUMPMACHINE', ''), 'dbus-1.0', 'include')]

        if 'CONFIG_CP0_LVGL_USE_ZMQ_LOG' in os.environ:
            DEFINITIONS += ['-DCP0_LVGL_USE_ZMQ_LOG=1']
            REQUIREMENTS += ['zmq']
        if 'CONFIG_CP0_LVGL_USE_ZMQ_RPC' in os.environ:
            DEFINITIONS += ['-DCP0_LVGL_USE_ZMQ_RPC=1']
            if 'zmq' not in REQUIREMENTS:
                REQUIREMENTS += ['zmq']

    env["COMPONENTS"].append(
        {
            "target": os.path.basename(env["component_dir"]),
            "SRCS": SRCS,
            "INCLUDE": INCLUDE,
            "PRIVATE_INCLUDE": PRIVATE_INCLUDE,
            "REQUIREMENTS": REQUIREMENTS,
            "STATIC_LIB": STATIC_LIB,
            "DYNAMIC_LIB": DYNAMIC_LIB,
            "DEFINITIONS": DEFINITIONS,
            "DEFINITIONS_PRIVATE": DEFINITIONS_PRIVATE,
            "LDFLAGS": LDFLAGS,
            "LINK_SEARCH_PATH": LINK_SEARCH_PATH,
            "REGISTER": "static",
        }
    )
