// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#include "ui.h"
#include <stdio.h>
#include <sys/stat.h>
#include "lvgl/src/widgets/gif/lv_gif.h"
#include "cp0_lvgl_app.h"
#include "sample_log.h"
///////////////////// VARIABLES ////////////////////



// SCREEN: ui_Screen1




#undef UI_DEFINE_OBJECT
#undef UI_DEFINE_EVENT_FUN
#define UI_DEFINE_OBJECT( x ) lv_obj_t * x ;
#define UI_DEFINE_EVENT_FUN(x) ;
#include "ui_obj.h"
#undef UI_DEFINE_OBJECT
#undef UI_DEFINE_EVENT_FUN

// CUSTOM VARIABLES
int Animation_time = 200;
const char *ui_img_zero_png;
const char *ui_img_time_png;
const char *ui_img_battery_bg_png;
const char *ui_img_left_png;
const char *ui_img_right_png;

const char *ui_img_store_logo_png;
const char *ui_img_cli_logo_png;
const char *ui_img_claw_logo_png;
const char *ui_img_setting_logo_png;
const char *ui_img_python_logo_png;

const char *ui_img_zero_logo_w_png;
const char *ui_img_left_logo_png;
const char *ui_img_right_logo_png;
const char *ui_img_detail_info_png;
const char *ui_img_down_logo_png;
const char *ui_img_up_logo_png;
const char *ui_img_camera_png;

static uint32_t EVT_TERM_KEY;

lv_font_t *g_font_cn_20 = NULL;
lv_font_t *g_font_cn_14 = NULL;
lv_font_t *g_font_cn_12 = NULL;
lv_font_t *g_font_mono_12 = NULL;   /* terminal-only monospaced font */
lv_font_t *g_font_bold_20 = NULL;   /* bold font for selected settings item */
lv_font_t *g_font_bold_14 = NULL;   /* bold app-name font - center */
lv_font_t *g_font_bold_12 = NULL;   /* bold app-name font - side */

// // EVENTS


///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif


///////////////////// FUNCTIONS ////////////////////



char* cimg_path(const char *name)
{
    static char path_buf[512];
    snprintf(path_buf, sizeof(path_buf), "%s", cp0_file_path(name));
    return path_buf;
}

char* caudio_path(const char *name)
{
    static char path_buf[512];
    snprintf(path_buf, sizeof(path_buf), "%s", cp0_file_path(name));
    return path_buf;
}

char* cfont_path(const char *name)
{
    static char path_buf[512];
    snprintf(path_buf, sizeof(path_buf), "%s", cp0_file_path(name));
    return path_buf;
}
