/*
 * SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
 *
 * SPDX-License-Identifier: MIT
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#include "ui.h"
#include "ui_app_page.hpp"
#include <stdio.h>
#include <cstdlib>
#include "lvgl/src/widgets/gif/lv_gif.h"
#include "cp0_lvgl_app.h"
#include "sample_log.h"

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

std::unique_ptr<LauncherUiRuntime> home;

namespace launcher_ui {

void init()
{
    home = std::make_unique<LauncherUiRuntime>();
    home->start();
}

} // namespace launcher_ui

LauncherFonts &launcher_fonts()
{
    if (!home) {
        std::abort();
    }
    return *home->fonts_;
}
