/*
 * SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
 *
 * SPDX-License-Identifier: MIT
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#ifndef _ZERO_UI_H
#define _ZERO_UI_H

#include "hal_lvgl_bsp.h"

#include "lvgl/lvgl.h"

/* APPLaunch's local LVGL FreeType override supports monochrome bitmap
 * rendering. Some SDK public headers expose the render mode type but not this
 * mode name, so keep the API name available to APPLaunch code. */
#ifndef LV_FREETYPE_FONT_RENDER_MODE_BITMAP_MONO
#define LV_FREETYPE_FONT_RENDER_MODE_BITMAP_MONO ((lv_freetype_font_render_mode_t)2)
#endif

#include "keyboard_input.h"
#include "cp0_lvgl_app.h"

// Launcher layout constants
#define BORDER_COLOR_CENTER 0x444444
#define BORDER_COLOR_SIDE 0x222222
#define LABEL_Y_CENTER 50
#define LABEL_Y_SIDE 50

#ifdef __cplusplus
#include <memory>
#include <string>
#include <unordered_map>

namespace launcher_ui {

namespace events {
inline const struct key_item *keyboard_item(lv_event_t *event)
{
    return static_cast<const struct key_item *>(lv_event_get_param(event));
}

inline uint32_t keyboard_key(lv_event_t *event)
{
    const struct key_item *item = keyboard_item(event);
    return item ? item->key_code : 0;
}

inline int keyboard_state(lv_event_t *event)
{
    const struct key_item *item = keyboard_item(event);
    return item ? item->key_state : 0;
}

inline bool is_key_pressed(lv_event_t *event)
{
    return lv_event_get_code(event) == static_cast<lv_event_code_t>(LV_EVENT_KEYBOARD) &&
           keyboard_state(event) > 0;
}

inline bool is_key_released(lv_event_t *event)
{
    return lv_event_get_code(event) == static_cast<lv_event_code_t>(LV_EVENT_KEYBOARD) &&
           keyboard_state(event) == 0;
}

inline lv_event_code_t battery_event()
{
    return static_cast<lv_event_code_t>(lv_c_event[CP0_C_EVENT_BATTERY]);
}

inline const cp0_battery_info_t *battery_info(lv_event_t *event)
{
    return static_cast<const cp0_battery_info_t *>(lv_event_get_param(event));
}
} // namespace events

void init();
}

class LauncherFonts
{
public:
    LauncherFonts() = default;
    ~LauncherFonts();

    lv_font_t *get(const char *ttf_name, uint16_t size, lv_freetype_font_style_t style);
    lv_font_t *get(const char *ttf_name, uint16_t size, lv_freetype_font_style_t style,
                   lv_freetype_font_render_mode_t render_mode);
    lv_font_t *get_mono(const char *ttf_name, uint16_t size, lv_freetype_font_style_t style);

private:
    void release();
    lv_font_t *fallback(uint16_t size) const;
    static std::string key(const char *ttf_name, uint16_t size, lv_freetype_font_style_t style,
                           lv_freetype_font_render_mode_t render_mode);

    std::unordered_map<std::string, lv_font_t *> fonts_;
};

LauncherFonts &launcher_fonts();
#ifndef APP_PAGE_IMPLEMENTATION_UNIT
#include "launch.h"
#include "ui_launch_page.h"
#include "launcher_ui_runtime.h"
#endif
#endif

#endif
