// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#ifndef _UI_INPUT_GROUP_H
#define _UI_INPUT_GROUP_H

#ifdef __cplusplus
extern "C" {
#endif

extern lv_group_t *Screen1group;

void input_group_init(void);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
