[ssh]
local_file_path = dist
remote_file_path = /home/pi/dist
remote_host = pi.local
remote_port = 22
username = pi
password = pi
; before_cmd = 'echo pi |  sudo -S pkill -f M5CardputerZero-UserDemo; sleep 1'
after_cmd = 'echo pi | sudo -S pkill -f M5CardputerZero-UserDemo || true; echo pi | sudo -S mkdir -p /usr/share/UserDemo/bin; echo pi | sudo -S install -m 755 /home/pi/dist/M5CardputerZero-UserDemo /usr/share/UserDemo/bin/M5CardputerZero-UserDemo; cd /usr/share/UserDemo; nohup ./bin/M5CardputerZero-UserDemo > /dev/null 2>&1 &'
