// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////



// SCREEN: ui_Screen1




#undef UI_DEFINE_OBJECT
#undef UI_DEFINE_EVENT_FUN
#define UI_DEFINE_OBJECT( x ) lv_obj_t * x ;
#define UI_DEFINE_EVENT_FUN(x) ;
#include "ui_obj.h"
#undef UI_DEFINE_OBJECT
#undef UI_DEFINE_EVENT_FUN

// CUSTOM VARIABLES
int Animation_time = 200;
const char *ui_img_zero_png = "A:/dist/images/zero.png";
const char *ui_img_time_png = "A:/dist/images/time.png";
const char *ui_img_zuo_png = "A:/dist/images/zuo.png";
const char *ui_img_you_png = "A:/dist/images/you.png";



const char *ui_img_store_logo_png = "A:/dist/images/Store_logo.png";
const char *ui_img_cli_logo_png = "A:/dist/images/CLI_logo.png";
const char *ui_img_claw_logo_png = "A:/dist/images/CLAW_logo.png";
const char *ui_img_setting_logo_png = "A:/dist/images/SETTING_logo.png";
const char *ui_img_python_logo_png = "A:/dist/images/PYTHON_logo.png";



const char *ui_img_zero_logo_w_png = "A:/dist/images/zero_logo_w.png";
const char *ui_img_zuo_logo_png = "A:/dist/images/zuo_logo.png";
const char *ui_img_you_logo_png = "A:/dist/images/you_logo.png";
const char *ui_img_detail_info_png = "A:/dist/images/detail_info.png";
const char *ui_img_down_logo_png = "A:/dist/images/down_logo.png";
const char *ui_img_up_logo_png = "A:/dist/images/up_logo.png";
const char *ui_img_camera_png = "A:/dist/images/camera.png";






const char * font_path = "./dist/images/AlibabaPuHuiTi-3-55-Regular.ttf";
const char * mono_font_path = "./dist/images/LiberationMono-Regular.ttf";





static uint32_t EVT_TERM_KEY;

lv_font_t *g_font_cn_20 = NULL;
lv_font_t *g_font_cn_14 = NULL;
lv_font_t *g_font_cn_12 = NULL;
lv_font_t *g_font_mono_12 = NULL;   /* 终端专用等宽字体 */

// // EVENTS


///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
#include "Animation/Animation_panel.h"

// ==================== Label Animations ====================
// Labels only animate x and y (no width/height change)
// 2you direction: labels slide right (pos5→6→7→8→9)

#include "Animation/Animation_lable.h"


///////////////////// FUNCTIONS ////////////////////
#define UI_DEFINE_UI_EVENT_FUN(event_fun, call_fun) __attribute__((weak)) void event_fun(lv_event_t * e) { \
    lv_event_code_t event_code = lv_event_get_code(e); \
    if(event_code == LV_EVENT_CLICKED) { \
        call_fun(e); \
    } \
}

#include "ui_event_fun.h"



#undef UI_DEFINE_UI_EVENT_FUN



void font_manager_init(void)
{
    
    g_font_cn_20 = lv_freetype_font_create(
        font_path, LV_FREETYPE_FONT_RENDER_MODE_BITMAP, 20,
        LV_FREETYPE_FONT_STYLE_NORMAL);

    g_font_cn_14 = lv_freetype_font_create(
        font_path, LV_FREETYPE_FONT_RENDER_MODE_BITMAP, 14,
        LV_FREETYPE_FONT_STYLE_NORMAL);

    g_font_cn_12 = lv_freetype_font_create(
        font_path, LV_FREETYPE_FONT_RENDER_MODE_BITMAP, 12,
        LV_FREETYPE_FONT_STYLE_BOLD);

    /* 终端专用等宽字体：LiberationMono 12px，字符宽度固定，适合终端字符网格 */
    
    g_font_mono_12 = lv_freetype_font_create(
        mono_font_path, LV_FREETYPE_FONT_RENDER_MODE_BITMAP, 12,
        LV_FREETYPE_FONT_STYLE_NORMAL);
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    font_manager_init(); // 先注释掉字体加载，测试UI能不能显示

    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();
    LV_EVENT_KEYBOARD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    // 初始化各个界面
    ui_Screen1_screen_init();



    // 界面信息绑定
    ui_info_bind();
    launch_circle_init();

    // 初始化输入组
    input_group_init();

    // 显示 home 界面
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
    lv_indev_set_group(lv_indev_get_next(NULL), Screen1group);
}
